## Tugas UAS | Jakarta Air Polution

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, confusion_matrix,accuracy_score, classification_report

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/dickyardianto08/dataset/main/jakarta_air_polution.csv')
df.head()

      tanggal             stasiun pm10 so2  co  o3 no2   max critical categori
0  2020-01-01  DKI1 (Bunderan HI)   30  20  10  32   9  32.0       O3     BAIK
1  2020-01-02  DKI1 (Bunderan HI)   27  22  12  29   8  29.0       O3     BAIK
2  2020-01-03  DKI1 (Bunderan HI)   39  22  14  32  10  39.0     PM10     BAIK
3  2020-01-04  DKI1 (Bunderan HI)   34  22  14  38  10  38.0       O3     BAIK
4  2020-01-05  DKI1 (Bunderan HI)   35  22  12  31   9  35.0     PM10     BAIK

In [ ]:
df = df[df.pm10 != "---"]
df = df[df.so2 != "---"]
df = df[df.o3 != "---"]
df = df[df.co != "---"]
df = df[df.no2 != "---"]
df = df[df.critical != "---"]
df = df[df.categori != "---"]
df.dropna(subset = ["critical"], inplace=True)
df.dropna(subset = ["max"], inplace=True)
df= df[df['max'] != 0]

In [ ]:
df.isnull().sum()

tanggal     0
stasiun     0
pm10        0
so2         0
co          0
o3          0
no2         0
max         0
critical    0
categori    0
dtype: int64

In [ ]:
df

,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,2020-01-01,DKI1 (Bunderan HI),30,20,10,32,9,32.0,O3,BAIK
1,2020-01-02,DKI1 (Bunderan HI),27,22,12,29,8,29.0,O3,BAIK
2,2020-01-03,DKI1 (Bunderan HI),39,22,14,32,10,39.0,PM10,BAIK
3,2020-01-04,DKI1 (Bunderan HI),34,22,14,38,10,38.0,O3,BAIK
4,2020-01-05,DKI1 (Bunderan HI),35,22,12,31,9,35.0,PM10,BAIK
...,...,...,...,...,...,...,...,...,...,...
1822,2020-12-24,DKI5 (Kebon Jeruk) Jakarta Barat,29,31,9,28,2,31.0,PM25,BAIK
1823,2020-12-25,DKI5 (Kebon Jeruk) Jakarta Barat,24,27,7,18,3,27.0,PM25,BAIK
1826,2020-12-28,DKI5 (Kebon Jeruk) Jakarta Barat,22,33,5,35,3,35.0,CO,BAIK
1828,2020-12-30,DKI5 (Kebon Jeruk) Jakarta Barat,16,7,3,21,2,21.0,CO,BAIK
1829,2020-12-31,DKI5 (Kebon Jeruk) Jakarta Barat,18,13,6,24,3,24.0,CO,BAIK

In [ ]:
df= df.drop(['stasiun','tanggal','critical','max'], axis=1)

In [ ]:
df

     pm10 so2  co  o3 no2 categori
0      30  20  10  32   9     BAIK
1      27  22  12  29   8     BAIK
2      39  22  14  32  10     BAIK
3      34  22  14  38  10     BAIK
4      35  22  12  31   9     BAIK
...   ...  ..  ..  ..  ..      ...
1822   29  31   9  28   2     BAIK
1823   24  27   7  18   3     BAIK
1826   22  33   5  35   3     BAIK
1828   16   7   3  21   2     BAIK
1829   18  13   6  24   3     BAIK

[1673 rows x 6 columns]

In [ ]:
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold,train_test_split,cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV
import xgboost as xgb

from sklearn.metrics import precision_score,recall_score
from sklearn.metrics import f1_score

In [ ]:
X=df.iloc[:,0:5].values
y=df.iloc[:,5].values

In [ ]:
X

array([['30', '20', '10', '32', '9'],
       ['27', '22', '12', '29', '8'],
       ['39', '22', '14', '32', '10'],
       ...,
       ['22', '33', '5', '35', '3'],
       ['16', '7', '3', '21', '2'],
       ['18', '13', '6', '24', '3']], dtype=object)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
import pickle
model = RandomForestClassifier()
model.fit(X_train, y_train)
# save the model to disk
filename = 'jakarta_polution.sav'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
models = [GaussianNB(), RandomForestClassifier(), KNeighborsClassifier()]
scores = dict()

for m in models:
    m.fit(X_train, y_train)
    y_pred = m.predict(X_test)

    print(f'model: {str(m)}')
    print(classification_report(y_test,y_pred, zero_division=1))
    print('-'*30, '\n')

model: GaussianNB()
              precision    recall  f1-score   support

        BAIK       0.93      0.82      0.87        96
      SEDANG       0.87      0.91      0.89       354
 TIDAK SEHAT       0.45      0.40      0.42        52

    accuracy                           0.84       502
   macro avg       0.75      0.71      0.73       502
weighted avg       0.84      0.84      0.84       502

------------------------------

model: RandomForestClassifier()
              precision    recall  f1-score   support

        BAIK       0.92      1.00      0.96        96
      SEDANG       1.00      0.97      0.99       354
 TIDAK SEHAT       0.98      0.98      0.98        52

    accuracy                           0.98       502
   macro avg       0.97      0.99      0.98       502
weighted avg       0.98      0.98      0.98       502

------------------------------

model: KNeighborsClassifier()
              precision    recall  f1-score   support

        BAIK       0.87      0.92      0.89        96
      SEDANG       0.96      0.96      0.96       354
 TIDAK SEHAT       1.00      0.87      0.93        52

    accuracy                           0.94       502
   macro avg       0.94      0.92      0.93       502
weighted avg       0.95      0.94      0.94       502

------------------------------

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).