# Tugas 2 | Diskritisasi

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
plt.ion()

In [11]:
dataset = "https://raw.githubusercontent.com/dickyardianto08/dataset/main/IRIS.csv"
data = pd.read_csv(dataset)

In [12]:
data.head(150)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
from sklearn.preprocessing import KBinsDiscretizer

In [14]:
sepalLength = data.sepal_length
sepalWidth = data.sepal_width
petalLength = data.petal_length
petalWidth = data.petal_width
spesies = data.species

In [15]:
aa = sepalLength.values.reshape(-1,1)
ab = sepalWidth.values.reshape(-1,1)
ac = petalLength.values.reshape(-1,1)
ad = petalWidth.values.reshape(-1,1)
sp = spesies.values.reshape(-1,1)

In [16]:
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [17]:
est.fit(aa)
est.fit(ab)
est.fit(ac)
est.fit(ad)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [18]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [19]:
KBinsDiscretizer(n_bins=Ellipsis)

KBinsDiscretizer(n_bins=Ellipsis)

In [20]:
xa = est.transform(aa)
xb = est.transform(ab)
xc = est.transform(ac)
xd = est.transform(ad)

In [21]:
dataa1 = {'sepal_length':xa}
dataa2 = {'sepal_length':xb}
dataa3 = {'sepal_length':xc}
dataa4 = {'sepal_length':xd}

In [22]:
fa = pd.DataFrame(xa,columns=['sepal_length'])
fb = pd.DataFrame(xb,columns=['sepal_width'])
fc = pd.DataFrame(xc,columns=['tepal_length'])
fd = pd.DataFrame(xd,columns=['tepal_width'])
spe = pd.DataFrame(sp,columns=['Species'])

In [23]:
datalist = [fa, fb, fc, fd, spe]
pd.concat(datalist, axis=1)

     sepal_length  sepal_width  tepal_length  tepal_width         Species
0             3.0          3.0           2.0          0.0     Iris-setosa
1             3.0          3.0           2.0          0.0     Iris-setosa
2             3.0          3.0           2.0          0.0     Iris-setosa
3             3.0          3.0           2.0          0.0     Iris-setosa
4             3.0          3.0           2.0          0.0     Iris-setosa
..            ...          ...           ...          ...             ...
145           3.0          3.0           3.0          3.0  Iris-virginica
146           3.0          3.0           3.0          3.0  Iris-virginica
147           3.0          3.0           3.0          3.0  Iris-virginica
148           3.0          3.0           3.0          3.0  Iris-virginica
149           3.0          3.0           3.0          2.0  Iris-virginica

[150 rows x 5 columns]